//
//  ChatModels.swift
//  SpeechToType
//
//  Data model of the chat: conversations, messages, attachments and the
//  provider/model a conversation talks to.
//

import Foundation

nonisolated enum ChatRole: String, Codable, Sendable {
    case user
    case assistant
}

/// A file attached to a user message. The file itself lives in the attachments
/// directory (see `ChatAttachmentStore`); the message only keeps this reference.
nonisolated struct ChatAttachment: Identifiable, Codable, Hashable, Sendable {
    enum Kind: String, Codable, Sendable {
        case image
        case pdf
        case text
    }

    let id: UUID
    let kind: Kind
    /// Original file name — shown in the UI and passed to the model
    let fileName: String
    /// Name of the copy inside the attachments directory
    let storedName: String
    let mimeType: String
}

nonisolated struct ChatMessage: Identifiable, Codable, Equatable, Sendable {
    let id: UUID
    let role: ChatRole
    var content: String
    var attachments: [ChatAttachment]
    let date: Date
    /// Display name of the model that wrote an assistant message
    var model: String?
    /// Set when generating this reply failed (partial text, if any, stays in `content`)
    var errorMessage: String?

    init(
        id: UUID = UUID(),
        role: ChatRole,
        content: String,
        attachments: [ChatAttachment] = [],
        date: Date = Date(),
        model: String? = nil,
        errorMessage: String? = nil
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.attachments = attachments
        self.date = date
        self.model = model
        self.errorMessage = errorMessage
    }
}

nonisolated struct ChatConversation: Identifiable, Codable, Equatable, Sendable {
    let id: UUID
    var title: String
    /// True once the title was generated by the model or set by the user
    var hasFinalTitle: Bool
    var model: ChatModelSelection
    var messages: [ChatMessage]
    let createdAt: Date
    var updatedAt: Date
}

/// Provider + model a chat talks to. The model is kept as a plain id so Ollama models
/// (free text) and models that are no longer offered still round-trip.
nonisolated struct ChatModelSelection: Codable, Hashable, Sendable {
    var provider: TextProcessingProvider
    var modelID: String

    var displayName: String {
        switch provider {
        case .openAI:
            return GPTModel(rawValue: modelID)?.displayName ?? modelID
        case .anthropic:
            return AnthropicModel(rawValue: modelID)?.displayName ?? modelID
        case .gemini:
            return GeminiModel(rawValue: modelID)?.displayName ?? modelID
        case .ollama:
            return modelID.isEmpty ? TextProcessingProvider.ollama.displayName : modelID
        case .appleIntelligence:
            return TextProcessingProvider.appleIntelligence.displayName
        }
    }

    /// The same selection with a model of an earlier generation replaced by its successor
    var upgraded: ChatModelSelection {
        let current: String?
        switch provider {
        case .openAI:
            current = GPTModel(storedValue: modelID)?.rawValue
        case .anthropic:
            current = AnthropicModel(storedValue: modelID)?.rawValue
        case .gemini:
            current = GeminiModel(storedValue: modelID)?.rawValue
        case .ollama, .appleIntelligence:
            current = nil
        }
        return ChatModelSelection(provider: provider, modelID: current ?? modelID)
    }
}

/// What is typed into a composer but not sent yet
struct ChatDraft: Equatable {
    var text = ""
    var attachments: [ChatAttachment] = []

    var isEmpty: Bool {
        text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && attachments.isEmpty
    }
}
